### ISSUE TITLE
1.41: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [Haivision/srt#1018]
Most important are strict aliasing and -Wlto-type-mismatch warnings which are causing that LTO cannot be applied on linking part of the code.

<pre>In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.cpp:77:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/cache.cpp:48:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/handshake.cpp:53:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/srt_c_api.cpp:23:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/srt_c_api.cpp: In function &apos;const char* srt_strerror(int, int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/srt_c_api.cpp:183:70: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
  183 |     e = CUDTException(CodeMajor(code/1000), CodeMinor(code%1000), err);
      |                                                                      ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/common.h:67,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/srt_c_api.cpp:22:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.cpp:55:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/congctl.cpp:30:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/crypto.cpp:26:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/buffer.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:63,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.cpp:60:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/packetfilter.h:19,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/packetfilter.cpp:18:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/transmitmedia.cpp:28:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/packetfilter.h:19,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/fec.cpp:17:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/api.h:60,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/api.cpp:60:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:59,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp: In copy constructor &apos;CUDT::CUDT(const CUDT&amp;)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:350:26: warning: implicitly-declared &apos;constexpr SrtCongestion&amp; SrtCongestion::operator=(const SrtCongestion&amp;)&apos; is deprecated [-Wdeprecated-copy]
  350 |     m_CongCtl = ancestor.m_CongCtl;
      |                          ^~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.h:71,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:68:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/congctl.h:81:5: note: because &apos;SrtCongestion&apos; has user-provided &apos;SrtCongestion::SrtCongestion(const SrtCongestion&amp;)&apos;
   81 |     SrtCongestion(const SrtCongestion&amp; source): congctl(), selector(source.selector) {}
      |     ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp: In member function &apos;void CUDT::startConnect(const sockaddr*, int32_t)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:3461:54: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 3461 |             e = CUDTException(MJ_SETUP, MN_TIMEOUT, 0);
      |                                                      ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:3472:51: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 3472 |         e = CUDTException(MJ_SETUP, MN_REJECTED, 0);
      |                                                   ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:3478:39: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 3478 |             e = CUDTException(MJ_SETUP);                   // XXX NO MN ?
      |                                       ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:3482:68: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 3482 |             e              = CUDTException(MJ_SETUP, MN_REJECTED, 0);
      |                                                                    ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:3485:55: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 3485 |             e = CUDTException(MJ_SETUP, MN_SECURITY, 0);
      |                                                       ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp: In member function &apos;EConnectStatus CUDT::postConnect(const CPacket&amp;, bool, CUDTException*, bool)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:4270:63: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 4270 |                 *eout = CUDTException(MJ_SETUP, MN_REJECTED, 0);
      |                                                               ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:4329:60: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 4329 |             *eout = CUDTException(MJ_NOTSUP, MN_SIDINVAL, 0);
      |                                                            ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp: In member function &apos;bool CUDT::prepareConnectionObjects(const CHandShake&amp;, HandshakeSide, CUDTException*)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:4969:61: warning: implicitly-declared &apos;CUDTException&amp; CUDTException::operator=(const CUDTException&amp;)&apos; is deprecated [-Wdeprecated-copy]
 4969 |             *eout = CUDTException(MJ_SYSTEMRES, MN_MEMORY, 0);
      |                                                             ^
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/channel.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/queue.h:57,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/core.cpp:67:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/udt.h:250:4: note: because &apos;CUDTException&apos; has user-provided &apos;CUDTException::CUDTException(const CUDTException&amp;)&apos;
  250 |    CUDTException(const CUDTException&amp; e);
      |    ^~~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/api.h:60,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/srt-tunnel.cpp:43:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h: In constructor &apos;sockaddr_any::sockaddr_any(int)&apos;:
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:40:37: warning: &apos;void* memset(void*, int, size_t)&apos; clearing an object of non-trivial type &apos;struct sockaddr_any&apos;; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/srtcore/netinet_any.h:28:8: note: &apos;struct sockaddr_any&apos; declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.hpp:30:7: warning: type &apos;struct Log&apos; violates the C++ One Definition Rule [-Wodr]
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.hpp:30:7: note: a different type is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.hpp:34:10: note: the first difference of corresponding definitions is field &apos;lockline&apos;
   34 |     bool lockline;
      |          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.hpp:30:7: note: a type with different number of fields is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.hpp:59:5: warning: type of &apos;__dt_comp &apos; does not match original declaration [-Wlto-type-mismatch]
   59 |     ~Log();
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.cpp:39:5: note: &apos;__dt_comp &apos; was previously declared here
   39 |     Log::~Log()
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.1/apps/verbose.cpp:39:5: note: code may be misoptimized unless &apos;-fno-strict-aliasing&apos; is used
</pre>

**Comment by ethouris** [comment]
What exactly options did you add to the compile command, beside `-Wlto-type-mismatch`, and what gcc version did you use?

**Comment by ethouris** [comment]
Checked with gcc 8.2.1. Not sure what version you are using, but latest master compiles cleanly with `-Wlto-type-mismatch`.

Also, there's no more any calls of `memcpy` in `netinet_any.h`.

**Comment by kloczek** [comment]
I'm using gcc 9.2.1 from Fedora rawhide.

**Comment by ethouris** [comment]
Wow. Oldest Highlanders didn't hear about this compiler. :)

Well, if you then be so kind and retry with the latest master, I'd be appreciated. I submitted there some fixes and there are also more to come (PR #1006 for example).

**Comment by kloczek** [comment]
That compiler is in use from ~6 months :P 
Nevertheless if you will look on lines reported by gcc you will find mismatches in declarations.

**Comment by ethouris** [comment]
As I told you, the problem is that these lines no longer exist in the master version. I'd be fine though, if the results can be replicated with gcc 8.2.1.

**Comment by maxsharabayko** [comment]
Closing as fixed by #1020

**Comment by kloczek** [comment]
I still see som ewarnings.
```
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.hpp:30:7: warning: type 'struct Log' violates the C++ One Definition Rule [-Wodr]
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.hpp:30:7: note: a different type is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.hpp:34:10: note: the first difference of corresponding definitions is field 'lockline'
   34 |     bool lockline = false;
      |          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.hpp:30:7: note: a type with different number of fields is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.hpp:56:5: warning: type of '__dt_comp ' does not match original declaration [-Wlto-type-mismatch]
   56 |     ~Log();
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.cpp:39:5: note: '__dt_comp ' was previously declared here
   39 |     Log::~Log()
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.3/apps/verbose.cpp:39:5: note: code may be misoptimized unless '-fno-strict-aliasing' is used
```
On `[-Wlto-type-mismatch]` is exposed by LTO.

**Comment by kloczek** [comment]
Just tested new 1.5.0 and stil lI see LTO related warnings
```console
[tkloczko@devel-g2v SPECS]$ rpmbuild -ba --with check --with failing_tests srt.spec --quiet 2>&1 | grep -- \\[-W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
      5 -Wdeprecated-declarations
      2 -Walloc-size-larger-than=
      1 -Wuninitialized
      1 -Wodr
      1 -Wlto-type-mismatch
```
In case of `-Wlto-type-mismatch` all what needs to be done is sync declaration of what is in .hpp header file and in .cpp.
Curent list of warnings
<details>

```console
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_AES_SetKey':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:43:9: warning: 'AES_set_encrypt_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   43 |         if (AES_set_encrypt_key(kstr, kstr_len * 8, aes_key)) {
      |         ^~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:51:5: note: declared here
   51 | int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
      |     ^~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:48:9: warning: 'AES_set_decrypt_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   48 |         if (AES_set_decrypt_key(kstr, kstr_len * 8, aes_key)) {
      |         ^~
/usr/include/openssl/aes.h:54:5: note: declared here
   54 | int AES_set_decrypt_key(const unsigned char *userKey, const int bits,
      |     ^~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_AES_CtrCipher':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:119:27: warning: 'AES_encrypt' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  119 |                           inlen, aes_key, iv, ctr, &blk_ofs, (block128_f) AES_encrypt);
      |                           ^~~~~
/usr/include/openssl/aes.h:57:6: note: declared here
   57 | void AES_encrypt(const unsigned char *in, unsigned char *out,
      |      ^~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_KmWrap':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:154:5: warning: 'AES_wrap_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  154 |     return(((seklen + HAICRYPT_WRAPKEY_SIGN_SZ) == (unsigned int)AES_wrap_key(kek, NULL, wrap, sek, seklen)) ? 0 : -1);
      |     ^~~~~~
/usr/include/openssl/aes.h:97:5: note: declared here
   97 | int AES_wrap_key(AES_KEY *key, const unsigned char *iv,
      |     ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_KmUnwrap':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/haicrypt/cryspr-openssl.c:166:5: warning: 'AES_unwrap_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  166 |     return(((wraplen - HAICRYPT_WRAPKEY_SIGN_SZ) == (unsigned int)AES_unwrap_key(kek, NULL, sek, wrap, wraplen)) ? 0 : -1);
      |     ^~~~~~
/usr/include/openssl/aes.h:101:5: note: declared here
  101 | int AES_unwrap_key(AES_KEY *key, const unsigned char *iv,
      |     ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/packet.cpp: In constructor 'srt::CPacket::CPacket()':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/packet.cpp:180:25: warning: member 'srt::CPacket::m_nHeader' is used uninitialized [-Wuninitialized]
  180 |     m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO])),
      |                         ^~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/queue.cpp: In member function 'init':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/queue.cpp:106:31: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  106 |         tempu = new CUnit[size];
      |                               ^
/usr/include/c++/12/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/queue.cpp: In member function 'increase':
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/srtcore/queue.cpp:172:31: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  172 |         tempu = new CUnit[size];
      |                               ^
/usr/include/c++/12/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.hpp:30:7: warning: type 'struct Log' violates the C++ One Definition Rule [-Wodr]
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.hpp:30:7: note: a different type is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.hpp:34:10: note: the first difference of corresponding definitions is field 'lockline'
   34 |     bool lockline = false;
      |          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.hpp:30:7: note: a type with different number of fields is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.hpp:56:5: warning: type of '__dt_comp ' does not match original declaration [-Wlto-type-mismatch]
   56 |     ~Log();
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.cpp:39:5: note: '__dt_comp ' was previously declared here
   39 |     Log::~Log()
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.5.0/apps/verbose.cpp:39:5: note: code may be misoptimized unless '-fno-strict-aliasing' is used
```
</details>

Is it possible to reopen this thicket?

**Comment by maxsharabayko** [comment]
Please see #2145.

**Comment by kloczek** [comment]
Gosh .. forgot to update ref in my BTS. Sorry 😋
